# Import Libraries

In [1]:
import zipfile
import pandas as pd
import csv
import json
import datetime

# Import Crime Data

In [2]:
crime_zip = zipfile.ZipFile("C:/Users/Barbieri/DSC-Program/DC-Criminalistics/dc-crime-data/dc-crime-data.csv.zip",
                            mode='r')
crime_csv = crime_zip.open('dc-crime-data.csv')

In [3]:
crime_df = pd.read_csv(crime_csv)

In [4]:
crime_df.head()

,NEIGHBORHOOD_CLUSTER,CENSUS_TRACT,offensegroup,LONGITUDE,END_DATE,offense-text,SHIFT,YBLOCK,DISTRICT,WARD,...,BLOCK,START_DATE,CCN,OFFENSE,OCTO_RECORD_ID,ANC,REPORT_DAT,METHOD,location,LATITUDE
0,cluster 5,5500.0,property,-77.052353,2009-03-30T15:50:00.000,theft/other,evening,137490.0,2.0,2.0,...,2400 - 2499 block of m street nw,2009-03-30T05:30:00.000,9041857,theft/other,09041857-01,2A,2009-03-30T20:40:00.000Z,others,"38.905263228683658,-77.052355683742746",38.905255
1,cluster 4,202.0,property,-77.062857,2009-03-30T16:30:00.000,theft/other,evening,137621.0,2.0,2.0,...,1224 - 1299 block of wisconsin avenue nw,2009-03-30T16:20:00.000,9041858,theft/other,09041858-01,2E,2009-03-30T20:34:00.000Z,others,"38.906438143434897,-77.062859682010298",38.906430
2,cluster 17,1804.0,violent,-77.027957,2009-03-30T00:00:00.000,robbery,evening,143785.0,4.0,4.0,...,5900 - 5999 block of georgia avenue nw,2009-03-30T17:00:00.000,9041900,robbery,09041900-01,4A,2009-03-30T21:42:00.000Z,others,"38.961978891670213,-77.027959395242561",38.961971
3,cluster 14,1002.0,property,-77.076820,2009-03-30T07:30:00.000,motor vehicle theft,evening,141241.0,2.0,3.0,...,3810 - 3899 block of rodman street nw,2009-03-29T07:00:00.000,9041916,motor vehicle theft,09041916-01,3C,2009-03-30T22:52:00.000Z,others,"38.939039936788873,-77.076822116815663",38.939032
4,cluster 23,8904.0,property,-76.979941,2009-03-30T20:30:00.000,theft/other,evening,137077.0,5.0,5.0,...,1600 - 1699 block of maryland avenue ne,2009-03-30T18:40:00.000,9041927,theft/other,09041927-01,5D,2009-03-30T22:40:00.000Z,others,"38.901552788657312,-76.979942787227358",38.901545

# Import Weather Data

In [5]:
weather_zip = zipfile.ZipFile("C:/Users/Barbieri/DSC-Program/DC-Criminalistics/weather-data/crime-weather-data.zip",
                              mode='r')

weather_json = weather_zip.open('crime-weather-data.json')

weather_dict = json.load(weather_json)

In [6]:
weather_list = []

for weather in weather_dict:
    try:
        latitude = weather['latitude']
    except KeyError:
        latitude = ''

    try:
        longitude = weather['longitude']
    except KeyError:
        longitude = ''

    try:
        time = weather['currently']['time']
    except KeyError:
        time = ''

    try:
        summary = weather['currently']['summary']
    except KeyError:
        summary = ''

    try:
        icon = weather['currently']['icon']
    except KeyError:
        icon = ''
        
    try:
        precip_intensity = weather['currently']['precipIntensity']
    except KeyError:
        precip_intensity = ''
        
    try:
        precip_probability = weather['currently']['precipProbability']
    except KeyError:
        precip_probability = ''
        
    try:
        temp = weather['currently']['temperature']
    except KeyError:
        temp = ''

    try:
        app_temp = weather['currently']['apparentTemperature']
    except KeyError:
        app_temp = ''

    try:
        dew_point = weather['currently']['dewPoint']
    except KeyError:
        dew_point = ''
        
    try:
        humidity = weather['currently']['humidity']
    except KeyError:
        humidity = ''
        
    try:
        pressure = weather['currently']['pressure']
    except KeyError:
        pressure = ''
        
    try:
        wind_speed = weather['currently']['windSpeed']
    except KeyError:
        wind_speed = ''
        
    try:
        wind_gust = weather['currently']['windGust']
    except KeyError:
        wind_gust = ''
        
    try:
        wind_bearing = weather['currently']['windBearing']
    except KeyError:
        wind_bearing = ''
        
    try:
        cloud_cover = weather['currently']['cloudCover']
    except KeyError:
        cloud_cover = ''        

    try:
        uv_index = weather['currently']['uvIndex']
    except KeyError:
        uv_index = ''

    try:
        visibility = weather['currently']['visibility']
    except KeyError:
        visibility = ''
    
    weather_list.append([latitude,longitude,time,
                         temp,app_temp,precip_probability,
                         humidity,cloud_cover,uv_index,
                         summary,icon,precip_intensity,
                         dew_point,pressure,wind_speed,
                         wind_gust,wind_bearing,cloud_cover,visibility])

In [7]:
columns = ['latitude','longitude','time',
           'temp','app_temp','precip_probability',
           'humidity','cloud_cover','uv_index',
           'summary','icon','precip_intensity',
           'dew_point','pressure','wind_speed',
           'wind_gust','wind_bearing','cloud_cover','visibility']

weather_df = pd.DataFrame(data=weather_list, columns=columns)

In [8]:
weather_df.head()

,latitude,longitude,time,temp,app_temp,precip_probability,humidity,cloud_cover,uv_index,summary,icon,precip_intensity,dew_point,pressure,wind_speed,wind_gust,wind_bearing,cloud_cover,visibility
0,38.9053,-77.0524,1238405400,46.54,43.43,0,0.54,1,0,Overcast,cloudy,0,30.6,1005.88,6.22,15.25,294,1,6.28
1,38.9064,-77.0629,1238444400,57.1,57.1,0,0.35,0.17,3,Clear,clear-day,0,29.94,1012.76,8.43,19.51,311,0.17,5.15
2,38.962,-77.028,1238446800,56.44,56.44,0,0.37,0.12,2,Clear,clear-day,0,30.33,1012.9,8.11,18.43,308,0.12,4.79
3,38.939,-77.0768,1238324400,47.9,47.9,0.32,0.98,1,0,Foggy,fog,0.0019,47.4,999.52,0.72,2.65,65,1,1.18
4,38.9015,-76.9799,1238452800,55.91,55.91,0,0.37,0.06,0,Clear,clear-day,0,30.21,1014.33,7.44,16.67,313,0.06,4.71

# Merge Crime and Weather Data

### Compare Dataframes

Notice that there are 13,967 more instances of crime than there are of the weather data. it will be important to note which instances of crime are missing.

In [9]:
weather_df_len = len(weather_df)
crime_df_len = len(crime_df)

print(weather_df_len, crime_df_len, weather_df_len-crime_df_len)

380053 381067 -1014

### Clean Weather Data

In [10]:
#There are missing rows.
weather_df = weather_df[weather_df['time'] != '']

#There are negative time values.
weather_df = weather_df[weather_df['time'] > 0]

In [11]:
#Convert time to match crime data.
def converttime(row):
    time = datetime.datetime.fromtimestamp(row).strftime('%Y-%m-%dT%H:%M:%S.000')

    return time

In [12]:
weather_df['c_time'] = weather_df['time'].apply(converttime)

In [13]:
weather_df.head()

,latitude,longitude,time,temp,app_temp,precip_probability,humidity,cloud_cover,uv_index,summary,icon,precip_intensity,dew_point,pressure,wind_speed,wind_gust,wind_bearing,cloud_cover,visibility,c_time
0,38.9053,-77.0524,1238405400,46.54,43.43,0,0.54,1,0,Overcast,cloudy,0,30.6,1005.88,6.22,15.25,294,1,6.28,2009-03-30T05:30:00.000
1,38.9064,-77.0629,1238444400,57.1,57.1,0,0.35,0.17,3,Clear,clear-day,0,29.94,1012.76,8.43,19.51,311,0.17,5.15,2009-03-30T16:20:00.000
2,38.962,-77.028,1238446800,56.44,56.44,0,0.37,0.12,2,Clear,clear-day,0,30.33,1012.9,8.11,18.43,308,0.12,4.79,2009-03-30T17:00:00.000
3,38.939,-77.0768,1238324400,47.9,47.9,0.32,0.98,1,0,Foggy,fog,0.0019,47.4,999.52,0.72,2.65,65,1,1.18,2009-03-29T07:00:00.000
4,38.9015,-76.9799,1238452800,55.91,55.91,0,0.37,0.06,0,Clear,clear-day,0,30.21,1014.33,7.44,16.67,313,0.06,4.71,2009-03-30T18:40:00.000

In [14]:
crime_weather_merge = crime_df.merge(weather_df,
                                     how='left',
                                     left_on=['LATITUDE','LONGITUDE','START_DATE'],
                                     right_on=['latitude','longitude','c_time'])

In [15]:
crime_weather_merge.head()

,NEIGHBORHOOD_CLUSTER,CENSUS_TRACT,offensegroup,LONGITUDE,END_DATE,offense-text,SHIFT,YBLOCK,DISTRICT,WARD,...,icon,precip_intensity,dew_point,pressure,wind_speed,wind_gust,wind_bearing,cloud_cover,visibility,c_time
0,cluster 5,5500.0,property,-77.0524,2009-03-30T15:50:00.000,theft/other,evening,137490.0,2.0,2.0,...,cloudy,0,30.6,1005.88,6.22,15.25,294,1,6.28,2009-03-30T05:30:00.000
1,cluster 4,202.0,property,-77.0629,2009-03-30T16:30:00.000,theft/other,evening,137621.0,2.0,2.0,...,clear-day,0,29.94,1012.76,8.43,19.51,311,0.17,5.15,2009-03-30T16:20:00.000
2,cluster 17,1804.0,violent,-77.028,2009-03-30T00:00:00.000,robbery,evening,143785.0,4.0,4.0,...,clear-day,0,30.33,1012.9,8.11,18.43,308,0.12,4.79,2009-03-30T17:00:00.000
3,cluster 14,1002.0,property,-77.0768,2009-03-30T07:30:00.000,motor vehicle theft,evening,141241.0,2.0,3.0,...,fog,0.0019,47.4,999.52,0.72,2.65,65,1,1.18,2009-03-29T07:00:00.000
4,cluster 23,8904.0,property,-76.9799,2009-03-30T20:30:00.000,theft/other,evening,137077.0,5.0,5.0,...,clear-day,0,30.21,1014.33,7.44,16.67,313,0.06,4.71,2009-03-30T18:40:00.000